.\"
.\" Copyright 2003-2020 Hiroki Sato <hrs@allbsd.org>.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd November 26, 2020
.Dt ANONGITSSH 1
.Os
.Sh NAME
.Nm anongitssh
.Nd restricted shell for git-upload-pack over SSH
.Sh SYNOPSIS
.Nm
.Fl c
git-upload-pack
.Ar repodir
.Sh DESCRIPTION
The
.Nm
utility is a restricted shell which invokes
.Xr git-upload-pack 1
utility included in the
.Xr git 1
suite.
It is designed to be a non-interactive login shell of a user on
the system which accepts read-only remote access via SSH protocol.
.Pp
The
.Nm
has a database of login names,
.Xr git 1
repository prefixes,
and
.Xr chroot 8
directories which is configurable at compile time.
When the 
.Nm
is invoked as a login shell,
it will check validity of the login name and the uid using the database,
do
.Xr chroot 8
to the directory specified in the database,
prepend a prefix to the pathname specified in
.Ar repodir ,
and finally invoke
.Xr git-upload-pack
with the complete pathname for the repository.
.Pp
All of the option flags passed from the client and environment variables
will be removed.
When an invalid access is detected,
a predefined message will be sent to the client.
.Sh LOGGING
The
.Nm
records all of the access via
.Xr syslog 3
API.
.Sh AUTHORS
The
.Nm
was written by
.An Hiroki Sato Aq Mt hrs@FreeBSD.org .
